name: Publish Release

on:
  workflow_call:

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: MetaMask/action-publish-release@35f8cf6223596548250502f22b6ece7117b54952
        id: publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          yarn install --immutable
          yarn build
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./packages/**/dist
            ./node_modules
          key: ${{ github.sha }}

  npm-publish-dry-run:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./packages/**/dist
            ./node_modules
          key: ${{ github.sha }}
      - run: npm config set ignore-scripts true
      - name: Dry Run Publish
        uses: MetaMask/action-npm-publish@v3
